-- Seed Atlas universe (single source of truth — frontend pulls from /api/universe).
-- Idempotent: re-running updates names/industries without losing analysis history.

INSERT INTO universe(ticker,name,exchange,industry,sector,pe,market_cap,active) VALUES
-- Mining
('ABX','Barrick Gold Corp','NYSE','Gold Mining',           'mining',  16.4, 33000, 1),
('NEM','Newmont Corporation','NYSE','Gold Mining',          'mining',  18.1, 42000, 1),
('AEM','Agnico Eagle Mines','NYSE','Gold Mining',           'mining',  19.7, 36000, 1),
('WPM','Wheaton Precious Metals','NYSE','Streaming',        'mining',  29.2, 25000, 1),
('TECK','Teck Resources Ltd','NYSE','Diversified Mining',    'mining',  9.8,  18000, 1),
('FCX','Freeport-McMoRan Inc','NYSE','Copper & Gold',        'mining',  22.0, 60000, 1),
('RIO','Rio Tinto Group','NYSE','Diversified Mining',        'mining',  9.4,  108000,1),
('BHP','BHP Group Ltd','NYSE','Diversified Mining',          'mining',  11.3, 145000,1),
('VALE','Vale S.A.','NYSE','Iron Ore & Nickel',              'mining',  6.1,  52000, 1),
('KGC','Kinross Gold Corp','NYSE','Gold Mining',             'mining',  14.2, 11000, 1),
('PAAS','Pan American Silver','NYSE','Silver Mining',         'mining',  31.0, 7000,  1),
('AG','First Majestic Silver','NYSE','Silver Mining',         'mining',  0,     2000,  1),
('FNV','Franco-Nevada Corp','NYSE','Royalty',                 'mining',  41.0, 27000, 1),
('SLI','Standard Lithium','NYSE','Lithium Mining',            'mining',  0,     400,   1),
('LAC','Lithium Americas','NYSE','Lithium Mining',            'mining',  0,     800,   1),
('ALB','Albemarle Corp','NYSE','Lithium',                     'mining',  0,     11000, 1),
('MP','MP Materials Corp','NYSE','Rare Earth',                'mining',  0,     2500,  1),
('SCCO','Southern Copper Corp','NYSE','Copper Mining',         'mining',  21.5, 80000, 1),
('AA','Alcoa Corporation','NYSE','Aluminum',                   'mining',  0,     6500,  1),
-- AI
('PLTR','Palantir Technologies','NYSE','Defense AI',          'ai',      130,  170000,1),
('AI','C3.ai Inc','NYSE','Enterprise AI',                      'ai',      0,    3500,  1),
('PATH','UiPath Inc','NYSE','RPA + AI',                        'ai',      0,    7500,  1),
('SOUN','SoundHound AI Inc','NYSE','Conversational AI',         'ai',      0,    4000,  1),
('BBAI','BigBear.ai Holdings','NYSE','Decision Intelligence',   'ai',      0,    1100,  1),
('SNOW','Snowflake Inc','NYSE','Data + AI',                     'ai',      0,    60000, 1),
('CRWD','CrowdStrike Holdings','NYSE','AI Cybersecurity',       'ai',      82.0, 110000,1),
('DDOG','Datadog Inc','NYSE','AI Monitoring',                   'ai',      78.0, 42000, 1),
('NVDA','NVIDIA Corporation','NYSE','AI Chips',                 'ai',      45.0, 3500000,1),
('AMD','Advanced Micro Devices','NYSE','AI Semiconductors',      'ai',      48.0, 230000,1),
('MSFT','Microsoft Corporation','NYSE','Cloud + AI',             'ai',      35.0, 3200000,1),
('GOOGL','Alphabet Inc','NYSE','Search + AI',                    'ai',      24.0, 2100000,1),
('META','Meta Platforms Inc','NYSE','Social + AI',                'ai',      26.0, 1500000,1),
('AMZN','Amazon.com Inc','NYSE','Cloud + AI',                     'ai',      45.0, 2000000,1),
('UPST','Upstart Holdings','NYSE','AI Lending',                   'ai',      0,    3000,  1),
('S','SentinelOne Inc','NYSE','AI Cybersecurity',                'ai',      0,    7500,  1),
('AAPL','Apple Inc','NYSE','Consumer AI',                          'ai',      32.0, 3500000,1),
('MDB','MongoDB Inc','NYSE','AI Database',                          'ai',      0,    20000, 1),
('TSLA','Tesla Inc','NYSE','AI + Autonomous',                       'ai',      62.0, 850000, 1),
-- Tech
('OTEX','Open Text Corp','NYSE','Enterprise Software',            'tech',    11.0, 7500,  1),
('GDDY','GoDaddy Inc','NYSE','Web Services',                       'tech',    24.0, 22000, 1),
('SHOP','Shopify Inc','NYSE','E-Commerce Platform',                 'tech',    65.0, 110000,1),
('ANET','Arista Networks','NYSE','Cloud Networking',                'tech',    35.0, 110000,1),
('CSU','Constellation Software','TSX','Vertical Market Software',    'tech',    72.0, 65000, 1),
('TSM','Taiwan Semiconductor','NYSE','Foundry',                      'tech',    24.0, 700000,1),
('CRM','Salesforce Inc','NYSE','Enterprise CRM',                      'tech',    45.0, 290000,1),
('ORCL','Oracle Corporation','NYSE','Cloud + Database',                'tech',    32.0, 380000,1),
('PANW','Palo Alto Networks','NYSE','Cybersecurity',                   'tech',    90.0, 110000,1),
('NOW','ServiceNow Inc','NYSE','IT Workflow',                          'tech',    105,  175000,1),
('AVGO','Broadcom Inc','NYSE','Semiconductors',                         'tech',    35.0, 1000000,1),
('INTC','Intel Corporation','NYSE','Semiconductors',                    'tech',    0,    90000, 1),
('ADBE','Adobe Inc','NYSE','Creative Software',                          'tech',    35.0, 220000,1),
('UBER','Uber Technologies','NYSE','Mobility',                           'tech',    24.0, 150000,1),
('NET','Cloudflare Inc','NYSE','Edge Computing',                          'tech',    0,    35000, 1),
('ZS','Zscaler Inc','NYSE','Cloud Security',                              'tech',    0,    30000, 1),
('TEAM','Atlassian Corp','NYSE','DevOps',                                 'tech',    0,    50000, 1),
('MRVL','Marvell Technology','NYSE','Data Infrastructure Chips',           'tech',    52.0, 75000, 1),
('DELL','Dell Technologies','NYSE','Enterprise Hardware',                   'tech',    21.0, 80000, 1),
('HPE','Hewlett Packard Enterprise','NYSE','Enterprise Infrastructure',     'tech',    11.0, 25000, 1),
-- Biotech
('MRNA','Moderna Inc','NYSE','mRNA',                                       'biotech', 0,    14000, 1),
('CRSP','CRISPR Therapeutics','NYSE','Gene Editing',                       'biotech', 0,    4000,  1),
('BNTX','BioNTech SE','NYSE','mRNA + Cancer',                              'biotech', 0,    25000, 1),
('ABCL','AbCellera Biologics','NYSE','Antibody AI',                         'biotech', 0,    700,   1),
('VRTX','Vertex Pharmaceuticals','NYSE','Gene Therapy',                     'biotech', 24.0, 110000,1),
('RXRX','Recursion Pharma','NYSE','AI Drug Discovery',                       'biotech', 0,    1700,  1),
('REGN','Regeneron Pharmaceuticals','NYSE','Therapeutics',                   'biotech', 22.0, 90000, 1),
('BIIB','Biogen Inc','NYSE','Neuroscience',                                  'biotech', 16.0, 25000, 1),
('GILD','Gilead Sciences','NYSE','Antiviral + Oncology',                      'biotech', 12.0, 100000,1),
('AMGN','Amgen Inc','NYSE','Large-Cap Biotech',                              'biotech', 22.0, 175000,1),
('LLY','Eli Lilly and Company','NYSE','GLP-1 + Diabetes',                    'biotech', 70.0, 700000,1),
('PFE','Pfizer Inc','NYSE','Big Pharma',                                      'biotech', 14.0, 165000,1),
('JNJ','Johnson & Johnson','NYSE','Diversified Healthcare',                   'biotech', 16.0, 380000,1),
('ABBV','AbbVie Inc','NYSE','Immunology + Oncology',                          'biotech', 18.0, 320000,1),
('BMY','Bristol-Myers Squibb','NYSE','Oncology + Cardio',                     'biotech', 0,    115000,1),
('ILMN','Illumina Inc','NYSE','Genomic Sequencing',                           'biotech', 0,    20000, 1),
('IONS','Ionis Pharmaceuticals','NYSE','RNA Therapeutics',                    'biotech', 0,    6000,  1),
('EXAS','Exact Sciences','NYSE','Cancer Diagnostics',                          'biotech', 0,    11000, 1),
('NTLA','Intellia Therapeutics','NYSE','In-Vivo Editing',                      'biotech', 0,    1500,  1),
('BEAM','Beam Therapeutics','NYSE','Base Editing',                             'biotech', 0,    1800,  1),
-- Energy
('SU','Suncor Energy','NYSE','Oil Sands',                                     'energy',  9.0,  55000, 1),
('CCJ','Cameco Corporation','NYSE','Uranium Mining',                           'energy',  85.0, 22000, 1),
('CNQ','Canadian Natural Resources','NYSE','Oil & Gas',                        'energy',  10.0, 80000, 1),
('ENB','Enbridge Inc','NYSE','Pipeline + Midstream',                            'energy',  19.0, 100000,1),
('XOM','Exxon Mobil Corporation','NYSE','Integrated Oil & Gas',                 'energy',  13.0, 480000,1),
('FSLR','First Solar Inc','NYSE','Solar Manufacturing',                          'energy',  18.0, 22000, 1),
('CVX','Chevron Corporation','NYSE','Integrated Oil & Gas',                      'energy',  14.0, 290000,1),
('COP','ConocoPhillips','NYSE','Exploration & Production',                       'energy',  12.0, 130000,1),
('NEE','NextEra Energy Inc','NYSE','Renewable + Utility',                        'energy',  19.0, 145000,1),
('OXY','Occidental Petroleum','NYSE','Oil & Gas + Carbon',                        'energy',  14.0, 50000, 1),
('DVN','Devon Energy Corp','NYSE','Shale',                                        'energy',  9.0,  25000, 1),
('PXD','Pioneer Natural Resources','NYSE','Permian E&P',                           'energy',  11.0, 60000, 1),
('ENPH','Enphase Energy','NYSE','Solar Microinverters',                            'energy',  35.0, 9000,  1),
('TRP','TC Energy Corporation','NYSE','Pipeline',                                  'energy',  18.0, 50000, 1),
('SLB','Schlumberger Ltd','NYSE','Oilfield Services',                              'energy',  14.0, 60000, 1),
('HAL','Halliburton Company','NYSE','Oilfield Services',                            'energy',  9.0,  25000, 1),
('SEDG','SolarEdge Technologies','NYSE','Solar Inverters',                          'energy',  0,    3000,  1),
('UEC','Uranium Energy Corp','NYSE','Uranium',                                       'energy',  0,    2500,  1),
('NXE','NexGen Energy Ltd','NYSE','Uranium Development',                             'energy',  0,    4000,  1),
('BE','Bloom Energy Corp','NYSE','Fuel Cells',                                       'energy',  0,    3500,  1),
-- Defense
('LMT','Lockheed Martin Corp','NYSE','Aerospace + Defense','defense',16.0,110000,1),
('GD','General Dynamics','NYSE','Defense + Aerospace','defense',20.0,75000,1),
('RTX','RTX Corporation','NYSE','Defense + Aerospace','defense',22.0,160000,1),
('CAE','CAE Inc','NYSE','Simulation + Training','defense',24.0,7000,1),
('AXON','Axon Enterprise Inc','NYSE','Law Enforcement Tech','defense',95.0,40000,1),
('NOC','Northrop Grumman Corp','NYSE','Aerospace + Defense','defense',19.0,75000,1),
('HII','Huntington Ingalls Industries','NYSE','Naval Shipbuilding','defense',13.0,9000,1),
('LHX','L3Harris Technologies','NYSE','Defense Electronics','defense',22.0,40000,1),
('BA','Boeing Company','NYSE','Aerospace + Defense','defense',0,110000,1),
('TDG','TransDigm Group','NYSE','Aerospace Components','defense',38.0,75000,1),
('HWM','Howmet Aerospace','NYSE','Aerospace Materials','defense',45.0,45000,1),
('LDOS','Leidos Holdings','NYSE','Defense IT','defense',16.0,18000,1),
('KTOS','Kratos Defense & Security','NYSE','Drone + Missile','defense',75.0,3000,1),
('RKLB','Rocket Lab USA','NYSE','Space Launch','defense',0,12000,1),
('ASTS','AST SpaceMobile','NYSE','Space-Based Broadband','defense',0,8000,1),
('BWXT','BWX Technologies','NYSE','Nuclear Tech','defense',24.0,9500,1),
('AVAV','AeroVironment Inc','NYSE','Military Drones','defense',0,5500,1),
('MRCY','Mercury Systems','NYSE','Defense Electronics','defense',0,2000,1),
('SPR','Spirit AeroSystems','NYSE','Aerospace Structures','defense',0,4000,1),
('GILT','Gilat Satellite Networks','NYSE','Satcom','defense',0,400,1),
-- Media
('DIS','Walt Disney Company','NYSE','Entertainment + Streaming','media',22.0,180000,1),
('NFLX','Netflix Inc','NYSE','Streaming','media',38.0,310000,1),
('SPOT','Spotify Technology','NYSE','Audio Streaming','media',75.0,90000,1),
('WBD','Warner Bros Discovery','NYSE','Media Conglomerate','media',0,22000,1),
('PARA','Paramount Global','NYSE','Media Conglomerate','media',0,8000,1),
('ROKU','Roku Inc','NYSE','Connected TV','media',0,8000,1),
('SNAP','Snap Inc','NYSE','Social Media','media',0,18000,1),
('PINS','Pinterest Inc','NYSE','Visual Discovery','media',26.0,22000,1),
('RDDT','Reddit Inc','NYSE','Social Platform','media',0,16000,1),
('RBLX','Roblox Corporation','NYSE','Gaming + Metaverse','media',0,30000,1),
('TTWO','Take-Two Interactive','NYSE','Video Games','media',0,28000,1),
('EA','Electronic Arts','NYSE','Video Games','media',32.0,38000,1),
('LYV','Live Nation Entertainment','NYSE','Live Events','media',58.0,22000,1),
('CMCSA','Comcast Corporation','NYSE','Cable + Media','media',9.0,160000,1),
('IMAX','IMAX Corporation','NYSE','Cinema Tech','media',24.0,1200,1),
-- Other
('V','Visa Inc','NYSE','Payment Networks','other',32.0,560000,1),
('SQ','Block Inc','NYSE','Fintech',          'other',24.0,40000,1),
('CNR','Canadian National Railway','NYSE','Rail','other',18.0,90000,1),
('WM','Waste Management Inc','NYSE','Environmental','other',32.0,80000,1),
('COST','Costco Wholesale','NYSE','Membership Retail','other',55.0,400000,1),
('BAM','Brookfield Asset Management','NYSE','Alt Asset Management','other',38.0,75000,1),
('MA','Mastercard Inc','NYSE','Payment Networks','other',38.0,440000,1),
('PYPL','PayPal Holdings','NYSE','Digital Payments','other',18.0,75000,1),
('COIN','Coinbase Global','NYSE','Crypto Exchange','other',0,55000,1),
('SOFI','SoFi Technologies','NYSE','Digital Banking','other',0,15000,1),
('CP','Canadian Pacific Kansas City','NYSE','Rail','other',24.0,75000,1),
('BRK.B','Berkshire Hathaway','NYSE','Diversified','other',12.0,900000,1),
('JPM','JPMorgan Chase','NYSE','Investment Banking','other',13.0,640000,1),
('GS','Goldman Sachs','NYSE','Investment Banking','other',16.0,170000,1),
('WMT','Walmart Inc','NYSE','Retail','other',32.0,550000,1)
ON CONFLICT(ticker) DO UPDATE SET
  name=excluded.name,
  exchange=excluded.exchange,
  industry=excluded.industry,
  sector=excluded.sector,
  pe=COALESCE(excluded.pe, universe.pe),
  market_cap=COALESCE(excluded.market_cap, universe.market_cap),
  active=excluded.active,
  updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now');
